// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt1zaPugl_SDmqLanPMS4NKKiiR1YOGMA',
    appId: '1:227026763113:web:6f939efa812def8a9f11f8',
    messagingSenderId: '227026763113',
    projectId: 'lost-and-found-5ecf3',
    authDomain: 'lost-and-found-5ecf3.firebaseapp.com',
    storageBucket: 'lost-and-found-5ecf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmhx81V_5f75EF-z8rMRD82b4DkjKdEHY',
    appId: '1:227026763113:android:01568092ef53a92b9f11f8',
    messagingSenderId: '227026763113',
    projectId: 'lost-and-found-5ecf3',
    storageBucket: 'lost-and-found-5ecf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOI_xo5ajnL9Igy_-9AwowbAtN_W72hd0',
    appId: '1:227026763113:ios:d79978a960e603d69f11f8',
    messagingSenderId: '227026763113',
    projectId: 'lost-and-found-5ecf3',
    storageBucket: 'lost-and-found-5ecf3.appspot.com',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOI_xo5ajnL9Igy_-9AwowbAtN_W72hd0',
    appId: '1:227026763113:ios:e0227874f9fc47519f11f8',
    messagingSenderId: '227026763113',
    projectId: 'lost-and-found-5ecf3',
    storageBucket: 'lost-and-found-5ecf3.appspot.com',
    iosBundleId: 'com.example.lostAndFound.RunnerTests',
  );
}
